### ISSUE TITLE
Can I use this project for working with Non HTTP calls? such as SNS topic notifications etc

### ISSUE THREAD

**Issue by Suedo** [rdlabo-team/serverless-nestjs#17]
First of all, Thank you for creating this project. Feels great to be able to use serverless with Nest, my favorite node framework :)
 
This post is not about an issue, but a question for which i didn't find a quick answer in google. Hoping to get it here :)

Let's say I have a lambda function that subscribes to a SNS topic, which is non http by nature, can we use this project to work with such scenarios as well ?

This [post](https://www.petermorlion.com/nestjs-aws-lambda-without-http/) explains how nestjs is http only by default, and how special configuration is needed to work with non-http events. 

They do this primarily by skipping `serverless-http`, but since this project uses `aws-serverless-express`, I was hoping it will be compatible with non-http events as well. 

Looking forward to some positive response 😊 
Thanks! 😊

**Comment by rdlabo** [comment]
You should prepare api point another handler and update serverless.yml.
This is sample:

```diff
  functions:
    index:
      handler: dist/src/index.handler
      events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
+   hours:
+     handler: dist/src/query/hours/index.handler
+     events:
+       - schedule: cron(0 23,0-11 * * ? *)
```
