### ISSUE TITLE
What does the script prestart:prod

### ISSUE THREAD

**Issue by frathi** [rdlabo-team/serverless-nestjs#21]
Hee. guys, thank you so much for this sample project. It helped me a lot so far.

I got a question. What does the script: prestart:prod which is mentioned in the README.md file? I can't find that script inside package.json. 

When I deploy my nest project I get the following error:
2020-10-09T08:59:02.612Z	a505539e-d746-4290-a1d3-cf7ccea3dccf	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "ENOENT: no such file or directory, mkdir '/var/task/src'",
    "code": "ENOENT",
    "errno": -2,
    "syscall": "mkdir",
    "path": "/var/task/src",
    "stack": [
        "Error: ENOENT: no such file or directory, mkdir '/var/task/src'"
    ]
}

thank you in advance

**Comment by rdlabo** [comment]
Thanks. This is before version script. I changed.
