### ISSUE TITLE
How do I access the event and context, in a NestJS way?

### ISSUE THREAD

**Issue by csterritt** [rdlabo-team/serverless-nestjs#4]
I'd like to be able to access the 'event' and 'context' that the lambda handler function takes as arguments in my NestJS code.  I don't see where they can be found... thanks!

**Comment by billkidwell** [comment]
The aws-serverless-express package includes middleware to access the context.

**Getting the API Gateway event object**
This package includes middleware to easily get the event object Lambda receives from API Gateway

```
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')
app.use(awsServerlessExpressMiddleware.eventContext())
app.get('/', (req, res) => {
  res.json(req.apiGateway.event)
})
```

Is there some other way you would like to access the context?

**Comment by rdlabo** [comment]
@billkidwell Thanks for great advice. other method:

```
app.use(yourMethod(awsServerlessExpressMiddleware.eventContext()))
```

This issues is for your reference:
https://github.com/nestjs/nest/issues/195
